OBJECTS = main.o memory.o patient.o process.o receptionist.o doctor.o

BIN_DIR = bin
INC_DIR = include
OBJ_DIR = obj
SRC_DIR = src

CC = gcc

memory.o: src/memory.c
	gcc -I include -o obj/memory.o -c src/memory.c
	
process.o: src/process.c
	gcc -I include -o obj/process.o -c src.process.c